POST http://localhost:3000/notifications HTTP/1.1
content-type: application/json

{  
    "recipientId": "{{$guid}}",
    "content": "Você tem uma nova solicitação de amizade - GG2. - {{$datetime rfc1123}}",
    "category": "social"
}